# =============================================================================
# XuanCe VEC Environment - SAC Configuration
# VEC边缘计算系统 - SAC算法配置
# =============================================================================

dl_toolbox: "torch"
project_name: "VEC_Edge_Computing"
logger: "tensorboard"
wandb_user_name: "vec_user"
render: false
render_mode: "rgb_array"
fps: 30
test_mode: false

device: "cuda:0"
distributed_training: false
master_port: "12355"

# SAC Algorithm settings
agent: "SAC"
env_name: "VEC"
env_id: "VEC-v1"
env_seed: 42
vectorize: "DummyVecEnv"
learner: "SAC_Learner"
policy: "Gaussian_SAC"
representation: "Basic_MLP"

# Network architecture
representation_hidden_size: [256, 256]
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "relu"
activation_action: "tanh"

seed: 42
parallels: 1

# Training settings
running_steps: 200000
start_training: 1000
training_frequency: 1

# SAC specific parameters
actor_learning_rate: 0.0003
critic_learning_rate: 0.0003
alpha_learning_rate: 0.0003
gamma: 0.99
tau: 0.005
batch_size: 256
buffer_size: 100000

# SAC entropy
alpha: 0.2
use_automatic_entropy_tuning: true
target_entropy: null  # Auto-compute based on action dim

# Gradient clipping
use_grad_clip: true
grad_clip_norm: 0.5

# Normalization
use_obsnorm: false
use_rewnorm: false
obsnorm_range: 5
rewnorm_range: 5

# Evaluation
test_steps: 10000
eval_interval: 10000
test_episode: 5

log_dir: "./logs/sac_vec/"
model_dir: "./models/sac_vec/"

# VEC Environment Settings
vec_config:
  num_vehicles: 12
  num_rsus: 4
  num_uavs: 2
  arrival_rate: 3.5
  max_episode_steps: 200
  use_enhanced_cache: true
  disable_migration: false
  reward_weight_delay: 0.5
  reward_weight_energy: 0.5
  reward_penalty_dropped: 1.0
